### ISSUE TITLE
[Suggestion] Progress indicator

### ISSUE THREAD

**Issue by RaddishIoW** [Serhioromano/vscode-gitflow#36]
It would be nice, if possible, to have some kind of progress indication for when the extension is doing something - like finishing a release.

At the moment, there is no indication that anything is happening, apart from maybe noticing the branch change in VS Code.

**Comment by Serhioromano** [comment]
Right now, I have only one process indicator when Sync all root branches. because that process takes some time. For other tasks I found it not practical. Other tasks are fust. In addition, VS Code does not have too many tools for indicating a process. The only additional window which is not quite appealing.

What would you expect? How to indicate? How to use indicator line on the viewlet title, I have not found. It only shows automaticaly when I refresh viewlet content.

**Comment by Serhioromano** [comment]
I have an idea. I can change Git Flow Icon in the status bar to spinner. What do you think? Would it be prominent enough indicator?

**Comment by RaddishIoW** [comment]
Hmm... yeah I see what you mean...

Yeah, I think that might help - at least some kind of animation in the status bar would show something was happening.
