### ISSUE TITLE
the characters # are supported when creating gitflow branch names

### ISSUE THREAD

**Issue by romanholidaypancakes** [Serhioromano/vscode-gitflow#37]
![image](https://user-images.githubusercontent.com/51652878/173230001-08b8ed6e-39e1-424f-aa41-cd104d78371a.png)

Sometimes `fix#123456` is used to fix a problem, and #1 can help us locate the problem, so this character should not be banned, nor does git itself ban this character

**Comment by Serhioromano** [comment]
If you add this to a comment of a fix like fix#123456 it will also do the same. Also, it is good practice to use a new version as a name for hotfix so that your application version tag is properly created. 

Anyway I change the name check to any fully valid gut branch name and in the comment I add also this issue so you will see how in a comment automatically works.

**Comment by Serhioromano** [comment]
I pushed version `1.3.11` it should work there. Should be available in market in a few minutes. 
Please, rate this extension if you few moments of time.
https://marketplace.visualstudio.com/items?itemName=Serhioromano.vscode-gitflow&ssr=false#review-details
